### ISSUE TITLE
#21-Bicicletes

### ISSUE THREAD

**Issue by aolle99** [Green-Wheel/Backend#24]
- [ ] #178: Obtenir informació bici completa
- [ ] #181: Guardar bicicleta nova
- [ ] #182: Guardar imatges a S3
- [ ] #185: Eliminar bicicleta
- [ ] #187: Obtenir punts bicicleta
- [ ] #189: Guardar punts bicicleta
