### ISSUE TITLE
#29-Registre usuari

### ISSUE THREAD

**Issue by aolle99** [Green-Wheel/Backend#35]
- [ ] #169: Guardar informació usuari
- [ ] #223: Enviar recuperació contrasenya
- [ ] #225: Guardar canvi de contrasenya
