### ISSUE TITLE
#37-Seleccionar idioma

### ISSUE THREAD

**Issue by aolle99** [Green-Wheel/Backend#4]
Com a usuari autenticat al sistema vull poder seleccionar l'idioma en què es mostran els texts de l'aplicació.
Tasques:

- [ ] #103 Interacció de seleccionar idioma
- [ ] #104 Creació de sistema d'internacionalització
- [ ] #138 Guardar selecció usuari/dispositiu per defecte
- [ ] #139 Obtenir idioma de l'usuari
