### ISSUE TITLE
#129-Obtenir punts de càrrega públic

### ISSUE THREAD

**Issue by crismigo** [Green-Wheel/Backend#5]
Tasques:

- [ ] #136 Fer sistema de sincronització entre API i còpia local
- [ ] #135 Guardar una copia local per tal d'evitar caigudes o problemes amb l'API
- [ ] #145 Fer crida a l'API per tal d'obtenir els carregadors
